Добавлены коментарии для моделей
securedevteam/Security-Door-Modeling pull request #13
Opened 2019-07-12 17:10 UTC by Borsuk7

2019-07-15 15:42 UTC, s207883 requested changes
Нужно поправить комментарии.

2019-07-15 15:42 UTC, s207883 commented on SecurityDoors.DAL/ViewModels/CardsUsingViewModel.cs
> +        /// Вызывает событие изменения свойства.
Вызывается при изменении свойства.

2019-07-15 15:42 UTC, s207883 commented on SecurityDoors.DAL/ViewModels/CardsUsingViewModel.cs
> +        /// <param name="prop">Имя вызывающего метода.</param>
Имя свойства

2019-07-15 15:42 UTC, s207883 commented on SecurityDoors.DAL/ViewModels/DataGridViewModel.cs
> +        /// Вызывает событие изменения свойства.
Тоже самое

2019-07-15 15:42 UTC, s207883 commented on SecurityDoors.DAL/ViewModels/PeopleAndCardsViewModel.cs
> +        /// Вызывает событие изменения свойства.
Тоже самое

2019-07-21 11:10 UTC, MikhailMasny reviewed
Доработать замечания.

2019-07-21 14:59 UTC, MikhailMasny commented
@s207883 Исправлено.

2019-07-21 15:00 UTC, MikhailMasny approved these changes
Проверено.

2019-07-22 18:28 UTC, s207883 approved these changes

2019-07-22 18:32 UTC, merged