NishikavaXUnitTests
securedevteam/Security-Door-Modeling pull request #14
Opened 2019-08-09 06:47 UTC by Nishikava

Исправлен проект для тестов.
Добавлены классы: ServiceFixture и DataManager.
Добавлен модификатор доступа public в интерфейсы слоя BLL.

2019-08-09 09:48 UTC, s207883 requested changes
Проект тестов создан на неправильном фреймворке. В проекте используется .net, а тесты на .net Core.
Переделать под правильный фрейм.

2019-08-09 09:57 UTC, MikhailMasny commented
Достаточно будет просто перевести на другой фреймворк и все. Тесты с нуля писать не нужно.

2019-08-09 09:57 UTC, Nishikava commented
Понял. Принял.

2019-08-09 21:38 UTC, MikhailMasny commented
@Nishikava Тесты я так понимаю не xUnit?

2019-08-11 10:56 UTC, s207883 reviewed
Тесты, я так понимаю, еще не задействованы?

2019-08-12 10:04 UTC, s207883 approved these changes
Принято

2019-08-12 19:58 UTC, merged