Refactoring console
securedevteam/Security-Door-Modeling pull request #7
Opened 2019-07-09 17:04 UTC by Borsuk7

2019-07-09 17:43 UTC, MikhailMasny commented on SecurityDoors.Core/Parser.cs
> +    public static class Parser
Почему статический класс? Где XML комментарий?

2019-07-09 17:43 UTC, MikhailMasny commented on SecurityDoors.Core/Parser.cs
> +        public static T ParseValueFromConsole<T>(string messege) where T : IConvertible
Синтаксическая ошибка в названии - message.

2019-07-09 17:45 UTC, MikhailMasny commented
Почему @s207883 не добавлен в качестве рецензента?

2019-07-09 17:45 UTC, MikhailMasny commented on SecurityDoors.Core/Parser.cs
> +                if (typeof(T) == typeof(int))
А если необходимо использовать тип long?

2019-07-09 17:47 UTC, MikhailMasny reviewed
Исправить замечания.

2019-07-09 17:53 UTC, MikhailMasny commented on SecurityDoors.Core/Parser.cs
> +            while (true)
И так и не понял, зачем цикл?

2019-07-09 17:54 UTC, MikhailMasny commented on SecurityDoors.UI.Console/MainController.cs
> +                if (await dataOperation.DownloadDataFromAPIAsync())
Ошибка! Верни как было и разберись, почему так правильно.

2019-07-09 18:05 UTC, MikhailMasny reviewed
Еще ряд исправлений.

2019-07-09 18:05 UTC, MikhailMasny commented on SecurityDoors.UI.Console/MainController.cs
> -            return connectionSettings;
Лучше вернуть в 2 строки, чем сразу отправлять return. Результат операции может еще понадобиться.

2019-07-09 18:05 UTC, MikhailMasny commented on SecurityDoors.UI.Console/MainController.cs
> -                result = await tcp.SendMessagesAsync(listOfMessages, delay, repeat);
Можно добавить сюда var, а строку 128 убрать.

2019-07-09 18:53 UTC, Borsuk7 commented on SecurityDoors.Core/Parser.cs
> +            while (true)
Цикл для повторного ввода если пользователь ввёл не верное значение

2019-07-10 14:09 UTC, s207883 requested changes

2019-07-10 14:09 UTC, s207883 commented on SecurityDoors.UI.Console/MainController.cs
>                  if (result)
В if(result) нет никакого смысла. Заменить на return result всю конструкцию.

2019-07-10 14:26 UTC, s207883 approved these changes

2019-07-11 19:13 UTC, MikhailMasny approved these changes
Есть замечания. Не создается экземпляр класса.

2019-07-11 19:13 UTC, merged